export const ORDERDETAIL_CONSTANTS = {
  SECTION: {
    ORDER_DETAIL: "주문 상세 내역",
    ORDER_PRODUCT: "주문 상품 정보",
    CUSTOMER: "주문자 정보",
    SHIPPING: "배송지 정보",
    PAYMENT: "결제 정보",
  },
  PROGRESS: {
    PAYMENT_PENDING: "입금대기",
    PAYMENT_COMPLETED: "결제완료",
    PRODUCT_PREPARING: "상품준비중",
    SHIPPING_START: "배송시작",
    SHIPPING: "배송중",
    DELIVERED: "배송완료",
  },
  ORDER: {
    DATE_LABEL: "주문일자",
    NUMBER_LABEL: "주문번호",
    DATE_VALUE: "2023-01-01",
    NUMBER_VALUE: "ORD20230101-1111111",
  },
  PRODUCT: {
    BRAND_1: "Apple",
    BRAND_2: "Banana",
    NAME: "DIGITAL WATCH",
    OPTION: "옵션: [사이즈] M, [색상] Navy",
    PRICE_1: "324,240원",
    PRICE_2: "648,480원",
    QUANTITY_1: "1개",
    QUANTITY_2: "2개",
  },
  SHIPPING: {
    LABEL: "배송비",
    FEE: "3,000원",
    EXPECTED_DATE: "2023.01.31 이내",
    STATUS: "출고 예정",
  },
  STATUS: {
    PAYMENT_COMPLETED: "결제 완료",
  },
  BUTTONS: {
    CANCEL: "취소 접수",
    INQUIRY: "1:1 문의",
  },
  CUSTOMER: {
    RECIPIENT: "수령인",
    PHONE: "휴대폰번호",
    EMAIL: "이메일",
    RECIPIENT_VALUE: "Koubit",
    PHONE_VALUE: "010-1***-1***",
    EMAIL_VALUE: "j*******@g*******.com",
  },
  SHIPPING_INFO: {
    RECIPIENT: "수령인",
    PHONE: "휴대폰번호",
    ADDRESS: "배송지",
    REQUEST: "배송 요청사항",
    RECIPIENT_VALUE: "Koubit",
    PHONE_VALUE: "010-1111-1111",
    ADDRESS_VALUE: "00000 한양시 조선구 고려동 11-1 신라아파트 111동 111호",
    REQUEST_VALUE: "파손 위험이 있으니 주의해서 취급 부탁드립니다.",
    CHANGE_BUTTON: "배송지 정보 변경",
  },
  PAYMENT: {
    METHOD: "결제 방법",
    ORDER_STATUS: "주문 상태",
    ORDER_DATE: "주문 접수 일시",
    PAYMENT_DATE: "결제 완료 일시",
    SHIPPING_FEE: "배송비",
    TOTAL_AMOUNT: "결제 금액",
    RECEIPT: "영수증",
    RECEIPT_BUTTON: "영수증 출력",
    METHOD_VALUE: "카카오페이",
    STATUS_VALUE: "결제 완료",
    ORDER_DATE_VALUE: "2023-01-01 18:00 PM",
    PAYMENT_DATE_VALUE: "2023-01-01 18:00 PM",
    SHIPPING_FEE_VALUE: "6,000원",
    TOTAL_AMOUNT_VALUE: "978,720원",
  },
  NOTICE: {
    TEXT_1:
      "* 상품이 품절되는 경우 주문이 자동으로 취소되며, 주문하신 분의 SMS와 이메일로 관련 안내를 발송해드립니다.",
    TEXT_2: "* 상세 내역은 마이페이지에서 확인하실 수 있습니다.",
  },
};
