export const ORDER_CONSTANTS = {
  PROGRESS: {
    STEP_1: "01 장바구니",
    STEP_2: "02 주문",
    STEP_3: "03 주문 확인",
  },
  SECTION: {
    PRODUCT_INFO: "주문 상품 정보",
    ORDERER_INFO: "주문자 정보",
    SHIPPING_INFO: "배송지 정보",
    COUPON_MILES: "쿠폰/마일리지",
    PAYMENT_DETAIL: "결제 상세",
    PAYMENT_METHOD: "결제 방법",
    AGREEMENT: "주문동의",
  },
  USER: {
    NAME: "이름",
    PHONE: "연락처",
    EMAIL: "이메일",
    EDIT: "수정",
  },
  SHIPPING: {
    DEFAULT: "기본 배송지",
    NEW: "신규 배송지",
    LIST: "배송지 목록",
    NAME: "배송지명",
    RECIPIENT: "수령인*",
    ADDRESS: "배송지*",
    PHONE1: "연락처1*",
    PHONE2: "연락처2",
    SET_DEFAULT: "기본 배송지로 등록",
    REQUIRED_TEXT: "*표시는 필수 입력 항목",
    REQUEST_PLACEHOLDER: "배송 시 요청사항을 선택해 주세요.",
    REQUEST_OPTIONS: {
      GUARD: "부재 시 경비실에 맡겨주세요",
      DOOR: "부재 시 문 앞에 놓아주세요",
      DIRECT: "직접 받겠습니다",
    },
    PLACEHOLDER: {
      NAME: "배송지명을 입력해주세요.",
      RECIPIENT: "수령인을 입력해주세요.",
      ADDRESS: "주소를 입력해주세요.",
      DETAIL_ADDRESS: "상세 주소를 입력해주세요.",
      PHONE: "010",
      PHONE_MIDDLE: "1234",
      PHONE_LAST: "5678",
    },
  },
  PRODUCT: {
    OPTION: "옵션: [사이즈] M, [색상] Navy",
    CURRENCY: "원",
    QUANTITY: "개",
    DISCOUNT: "[20%]",
  },
  COUPON: {
    BONUS: "보너스 쿠폰",
    BRAND: "브랜드 쿠폰",
    MILES: "마일리지",
    USE_ALL: "모두 사용",
    AVAILABLE: "사용 가능",
    HOLD: "보유",
    BONUS_COUPON: "사용 가능 쿠폰 3장 / 보유 4장",
    NO_COUPON: "적용 가능한 쿠폰이 없습니다.",
  },
  PAYMENT: {
    TOTAL_PRODUCT: "총 상품금액",
    COUPON_USE: "쿠폰 사용",
    MILES_USE: "마일리지 사용",
    SHIPPING_FEE: "배송비",
    TOTAL_AMOUNT: "총 결제금액",
    NOTICE: "신용/체크카드 안내",
    METHODS: {
      CREDIT_CARD: "신용/체크카드",
      HYUNDAI: "현대카드 X PIN PAY",
      TOSS: "토스페이",
      NAVER: "네이버페이",
      KAKAO: "카카오페이",
      SAMSUNG: "삼성페이",
      PAYCO: "페이코",
      SSG: "SSG페이",
      BANK: "무통장입금",
    },
    CARD_SELECT: "카드사를 선택해주세요.",
    BENEFIT: "혜택",
    BENEFITS: {
      TOSS: "[토스페이] 생애 첫 결제 1만원 이상 3천 토스페이 포인트 적립",
      KAKAO: "[카카오페이] 12만원 이상 6천원 즉시할인",
    },
    PAY_BUTTON: "결제하기",
  },
  AGREEMENT: {
    ALL: "주문 내용을 확인했으며, 아래 내용에 모두 동의합니다.",
    PERSONAL_INFO: "(필수) 개인정보 수집/이용 동의",
    THIRD_PARTY: "(필수) 개인정보 제 3자 제공 동의",
    PAYMENT: "(필수) 결제대행 서비스 이용약관",
    VIEW: "보기",
  },
  WARNINGS: {
    AGREEMENT_REQUIRED: "모든 약관에 동의해주세요.",
  },
};
