export const REGISTER_CONSTANTS = {
  AGREEMENT: {
    TITLE_LINE1: "환영합니다!",
    TITLE_LINE2: "GREGORI에 가입하시려면 서비스 이용약관에 동의해 주세요.",
    ALL_AGREEMENT: "약관 전체 동의하기(선택 동의 포함)",
    AGE_REQUIREMENT: "[필수] 만 14세 이상입니다.",
    TERMS_REQUIREMENT: "[필수] 이용약관 동의",
    TERMS_DETAIL: "자세히",
    MARKETING_OPTIONAL: "[선택] 마케팅 활용 동의",
    PROCEED_BUTTON: "동의하고 가입하기",
  },
  FORM: {
    TITLE: "회원가입",
    EMAIL_LABEL: "이메일",
    EMAIL_PLACEHOLDER: "이메일",
    PASSWORD_LABEL: "비밀번호",
    PASSWORD_PLACEHOLDER: "비밀번호",
    CONFIRM_PASSWORD_LABEL: "비밀번호 확인",
    CONFIRM_PASSWORD_PLACEHOLDER: "비밀번호 확인",
    NAME_LABEL: "이름",
    NAME_PLACEHOLDER: "이름",
    PHONE_LABEL: "휴대폰 번호",
    PHONE_PLACEHOLDER: "휴대폰 번호",
    VERIFICATION_LABEL: "인증번호",
    VERIFICATION_PLACEHOLDER: "인증번호",
    SUBMIT_BUTTON: "회원가입",
    ALREADY_ACCOUNT: "이미 계정이 있으신가요?",
    LOGIN_LINK: "로그인하기",
  },
  ERROR: {
    REQUIRED_AGREEMENT: "필수 약관에 동의해주세요.",
    PHONE_REQUIRED: "휴대폰 번호를 입력해주세요.",
    VERIFICATION_SEND_FAILED: "인증번호 전송에 실패했습니다.",
    VERIFICATION_CODE_REQUIRED: "인증번호를 입력해주세요.",
    VERIFICATION_FAILED: "인증번호가 올바르지 않습니다.",
    ALL_FIELDS_REQUIRED: "모든 필드를 입력해주세요.",
    PASSWORD_MISMATCH: "비밀번호가 일치하지 않습니다.",
    VERIFICATION_NOT_COMPLETED: "휴대폰 인증을 완료해주세요.",
    REGISTER_FAILED: "회원가입에 실패했습니다.",
  },
  SUCCESS: {
    REGISTER_COMPLETED: "회원가입이 완료되었습니다.",
  },
  EMAIL_DOMAINS: {
    GMAIL: "gmail.com",
    NAVER: "naver.com",
    DAUM: "daum.net",
    YAHOO: "yahoo.com",
  },
};
